version: '3.8'
services:
  app:
    build:
      context: . 
      dockerfile: docker/Dockerfile 
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_DIALECT}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - mysql
      - redis
    networks:
      - nestProject

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - nestProject
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - nestProject

networks:
  nestProject: 
